version: '3'

volumes:
   pgdb:

services:
  redis:
    image: redis

  postgres:
    image: postgres
    env_file:
      - .env
    environment:
      POSTGRES_DB: sentry
    volumes:
     - pgdb:/var/lib/postgresql/data

  sentry:
    build: ./sentry
    image: naari3/sentry_with_plugins
    links:
     - redis
     - postgres
    ports:
     - 9000:9000
    env_file:
      - .env
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis

  cron:
    build: ./sentry
    image: naari3/sentry_with_plugins
    links:
     - redis
     - postgres
    command: "sentry run cron"
    env_file:
      - .env
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis

  worker:
    build: ./sentry
    image: naari3/sentry_with_plugins
    links:
     - redis
     - postgres
    command: "sentry run worker"
    env_file:
      - .env
    environment:
      SENTRY_POSTGRES_HOST: postgres
      SENTRY_REDIS_HOST: redis
